// "Novidades": a non-technical changelog in plain language, for people who use
// Rabisco (not for developers). Update it whenever a change is worth telling
// users about; it does not mirror CHANGELOG.md (generated by release-please).
// Internal or admin-only tools never go here.
//
// The text lives in the dictionaries (src/i18n/*.ts, under whatsNew.sections)
// so it follows the user's language. Keep ONE entry per date, newest first:
// if today already has an entry, add a section to it instead of a new entry.
import type { Messages } from '../i18n/pt-BR'

export type WhatsNewSection = keyof Messages['whatsNew']['sections']

export interface WhatsNewEntry {
  date: string // yyyy-mm-dd; used for ordering and for the "unseen" dot
  sections: WhatsNewSection[]
}

export const whatsNewEntries: WhatsNewEntry[] = [
  { date: '2026-10-10', sections: ['mindmapExtras', 'home'] },
  { date: '2026-10-09', sections: ['mindmap', 'drive', 'launch'] },
]

export const latestWhatsNewDate: string | undefined = whatsNewEntries[0]?.date
