import { useI18n } from '../i18n/useI18n'

// Generated by `pnpm screenshots` (scripts/screenshots) into public/landing/, one per language and theme.
export type Shot = 'canvas' | 'mindmap' | 'draw' | 'files'

const SIZES: Record<Shot, { width: number; height: number }> = {
  canvas: { width: 1280, height: 800 },
  mindmap: { width: 700, height: 438 },
  draw: { width: 720, height: 450 },
  files: { width: 700, height: 415 },
}

export const screenshotPath = (lang: string, shot: Shot, theme: 'light' | 'dark') =>
  `/landing/${lang}-${shot}-${theme}.webp`

export function Screenshot({
  shot,
  alt,
  className,
  eager = false,
}: {
  shot: Shot
  alt: string
  className?: string
  eager?: boolean
}) {
  const { lang } = useI18n()
  return (
    <picture className={className}>
      <source srcSet={screenshotPath(lang, shot, 'dark')} media="(prefers-color-scheme: dark)" />
      <img
        src={screenshotPath(lang, shot, 'light')}
        alt={alt}
        {...SIZES[shot]}
        loading={eager ? 'eager' : 'lazy'}
        decoding="async"
      />
    </picture>
  )
}
